### ISSUE TITLE
Violates Chrome Web store policy...

### ISSUE THREAD

**Issue by max-allan-surevine** [prolane/samltoawsstskeys#52]
It violates some policy and has been removed. Which is annoying because it is very useful.

**Comment by max-allan-surevine** [comment]
I downloaded the source and "Add unpacked plugin" and have it working again!
I did try to update to a v3 manifest, but that needs a better understanding of how to write a plugin...   No access to the DOM in the script.js with v3.

**Comment by prolane** [comment]
Apparently Google took down my extension, because they need some explanation on the code, the permissions its using and a statement from me that I'm not collecting and selling data. I've answered all the required questions in their developer portal and submitted it for review. They say the review can take up to 30 days.

To be fair, Google did sent me a warning one month ago, but I missed it.

**Comment by prolane** [comment]
The extension is back in the Chrome Web Store with an updated version `2.8`. For now, the only code change in this version is removing the `tabs` permission since that was not required. Google is happy again; The policy violation error is gone.
