### ISSUE TITLE
Credential file not downloading after v3.0 upgrade

### ISSUE THREAD

**Issue by rajeevkrishnanv** [prolane/samltoawsstskeys#58]
The credentials file is not getting downloaded after latest update. Since the logs contain sensitive information, I'm posting masked screenshots. Hope that will help

![logs](https://user-images.githubusercontent.com/4892793/208147040-af729574-fa23-4867-bed7-4ff4640d8c92.png)
![error](https://user-images.githubusercontent.com/4892793/208147047-63a971c1-af42-461f-b004-958618e9edda.png)
![logs-rolelist](https://user-images.githubusercontent.com/4892793/208147054-dff8ea8f-278a-4a50-9f51-e1f5583c4644.png)

**Comment by Wildhammer** [comment]
Similar issue since this morning.

**Comment by pjbhaumik** [comment]
I am seeing the issue with chrome. It is working with Firefox still...  This means that there is an issue with the chrome compatibility.

**Comment by prolane** [comment]
Thanks @rajeevkrishnanv for posting the issue. Due to new Google policies I had to refactor the code quite a bit. Unfortunately such changes always introduce the risk of code breaking down in certain situations.

The issue is related to a new xml parser I'm using. Before I was using DOM selectors on the xml, but under new Google policies this is not possible anymore. Apparently there are some variations in how the SAML xml is structured. This results in a slightly different data object after parsing.

More specific;
In my code I'm expecting `attributes_role_list` to be a list of strings. Now it appears in some cases this list can be a list of objects, with each object having a key `#text` which holds the actual value (the string I'm expecting).

I have sufficient information to debug this issue. I'm out for the evening, but I'll fix this tomorrow morning.

**Comment by prolane** [comment]
> I am seeing the issue with chrome. It is working with Firefox still... This means that there is an issue with the chrome compatibility.

@pjbhaumik The FireFox extension is created from this code base, but I'm not maintaining it myself. The FireFox extension is still on a previous version. This is why this one still works.

I'll be working on a fix soon though.

**Comment by prolane** [comment]
I've submitted v3.1. When Google finishes the review, it will be automatically published to the web store.

The fix is primarily a changed configuration of the xmlparser. This should allow for a unified way of processing the the SAML Assertion Attributes, instead of having to code exceptions.

@rajeevkrishnanv, let me know once `v3.1` is available if this fixed the issue for you.

**Comment by joshbranham** [comment]
3.1 just updated for me and the file is downloading 👍

**Comment by rajeevkrishnanv** [comment]
Thanks a lot @prolane . It worked
